import {
  Award,
  BarChart2,
  Book,
  Box,
  Briefcase,
  Calendar,
  Camera,
  Compass,
  Disc,
  DollarSign,
  FileText,
  Film,
  Globe,
  UserCheck,
  Hexagon,
  Instagram,
  Laptop,
  Layers,
  Lightbulb,
  Mail,
  MessageCircle,
  Mic,
  Music,
  Palette,
  Radio,
  Rocket,
  Share2,
  Shuffle,
  Sliders,
  Smartphone,
  Speaker,
  Star,
  Target,
  TrendingUp,
  Tv,
  Users,
  Video,
  Wifi,
  Zap,
  LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  award: Award,
  chart: BarChart2,
  book: Book,
  box: Box,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  compass: Compass,
  disc: Disc,
  dollar: DollarSign,
  file: FileText,
  film: Film,
  globe: Globe,
  handshake: UserCheck,
  hexagon: Hexagon,
  instagram: Instagram,
  laptop: Laptop,
  layers: Layers,
  lightbulb: Lightbulb,
  mail: Mail,
  message: MessageCircle,
  mic: Mic,
  music: Music,
  palette: Palette,
  radio: Radio,
  rocket: Rocket,
  share: Share2,
  shuffle: Shuffle,
  sliders: Sliders,
  smartphone: Smartphone,
  speaker: Speaker,
  star: Star,
  target: Target,
  trending: TrendingUp,
  tv: Tv,
  users: Users,
  video: Video,
  wifi: Wifi,
  zap: Zap,
};

interface MissionIconProps {
  name: string;
  className?: string;
}

export function MissionIcon({ name, className = "" }: MissionIconProps) {
  const Icon = iconMap[name] || Box;
  return <Icon className={className} />;
}
